# Generated by Django 4.2.23 on 2025-09-22 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_jobsyncrun_jobsyncportalresult_jobsyncjobresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Machine_Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(help_text='Unique machine UUID', max_length=100, unique=True)),
                ('hostname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_authorized', models.BooleanField(default=True)),
                ('access_token', models.CharField(blank=True, max_length=100)),
                ('token_secret', models.CharField(blank=True, max_length=100)),
                ('total_transmissions', models.PositiveIntegerField(default=0)),
                ('successful_transmissions', models.PositiveIntegerField(default=0)),
                ('last_transmission_status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Machine Registry',
                'verbose_name_plural': 'Machine Registries',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Tbl_Node_Users',
            fields=[
                ('node_users_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('egc_user_id', models.IntegerField(blank=True, null=True)),
                ('profile_path', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Node User',
                'verbose_name_plural': 'Node Users',
            },
        ),
        migrations.CreateModel(
            name='Tbl_Job_Transmission_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_id', models.CharField(help_text='Unique ID for this transmission', max_length=50, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('jobs_sent', models.PositiveIntegerField(default=0)),
                ('updates_sent', models.PositiveIntegerField(default=0)),
                ('total_payload_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('was_encrypted', models.BooleanField(default=True)),
                ('encryption_method', models.CharField(default='Fernet', max_length=50)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to='jobs.tbl_machine_registry')),
            ],
            options={
                'verbose_name': 'Job Transmission Log',
                'verbose_name_plural': 'Job Transmission Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Tbl_Job_Transmission_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('new_job', 'New Job'), ('job_update', 'Job Update'), ('status_change', 'Status Change')], max_length=20)),
                ('was_successful', models.BooleanField(default=False)),
                ('error_details', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('payload_data', models.JSONField(blank=True, default=dict, help_text='The actual data sent for this job')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobposting')),
                ('transmission_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jobs.tbl_job_transmission_log')),
            ],
            options={
                'verbose_name': 'Job Transmission Item',
                'verbose_name_plural': 'Job Transmission Items',
                'ordering': ['-sent_at'],
            },
        ),
    ]
