# Generated by Django 4.2.16 on 2025-11-12 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0016_tbl_machine_registry_tbl_node_users_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiAdminToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_name",
                    models.CharField(
                        help_text="Friendly name for this token",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "token_key",
                    models.CharField(
                        help_text="The actual API key (hashed in production)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("can_trigger_etl", models.BooleanField(default=True)),
                ("can_view_logs", models.BooleanField(default=True)),
                ("can_manage_skills", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "API Admin Token",
                "verbose_name_plural": "API Admin Tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobIngestionSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_date", models.DateField(unique=True)),
                ("execution_started_at", models.DateTimeField(auto_now_add=True)),
                ("execution_finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_scraped",
                    models.PositiveIntegerField(
                        default=0, help_text="Total jobs scraped"
                    ),
                ),
                (
                    "total_processed",
                    models.PositiveIntegerField(
                        default=0, help_text="Successfully processed jobs"
                    ),
                ),
                (
                    "total_duplicates",
                    models.PositiveIntegerField(
                        default=0, help_text="Duplicate jobs skipped"
                    ),
                ),
                (
                    "total_errors",
                    models.PositiveIntegerField(
                        default=0, help_text="Processing errors"
                    ),
                ),
                (
                    "new_skills_added",
                    models.PositiveIntegerField(
                        default=0, help_text="New skills discovered"
                    ),
                ),
                ("jobs_with_salary", models.PositiveIntegerField(default=0)),
                ("jobs_with_skills", models.PositiveIntegerField(default=0)),
                ("jobs_with_location", models.PositiveIntegerField(default=0)),
                (
                    "source_breakdown",
                    models.JSONField(
                        blank=True, default=dict, help_text="Stats per scraping source"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("error_log", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Job Ingestion Summary",
                "verbose_name_plural": "Job Ingestion Summaries",
                "ordering": ["-summary_date"],
            },
        ),
        migrations.CreateModel(
            name="PortalJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash_key",
                    models.CharField(
                        help_text="Same hash as vault for linking",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                (
                    "description",
                    models.TextField(help_text="Cleaned and sanitized job description"),
                ),
                (
                    "company_display_name",
                    models.CharField(
                        help_text="Anonymised or generic company name", max_length=200
                    ),
                ),
                ("company_size", models.CharField(blank=True, max_length=50)),
                ("company_industry", models.CharField(blank=True, max_length=100)),
                ("location_city", models.CharField(blank=True, max_length=100)),
                ("location_state", models.CharField(blank=True, max_length=50)),
                (
                    "location_country",
                    models.CharField(default="Australia", max_length=50),
                ),
                ("location_remote", models.BooleanField(default=False)),
                ("job_category", models.CharField(blank=True, max_length=100)),
                (
                    "job_type",
                    models.CharField(
                        blank=True,
                        help_text="Full-time, Part-time, etc.",
                        max_length=50,
                    ),
                ),
                ("experience_level", models.CharField(blank=True, max_length=100)),
                (
                    "work_mode",
                    models.CharField(
                        blank=True, help_text="Remote, Hybrid, On-site", max_length=50
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("salary_currency", models.CharField(default="AUD", max_length=3)),
                (
                    "salary_type",
                    models.CharField(
                        default="yearly",
                        help_text="hourly, daily, weekly, monthly, yearly",
                        max_length=10,
                    ),
                ),
                (
                    "salary_display",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable salary string",
                        max_length=200,
                    ),
                ),
                (
                    "required_skills",
                    models.TextField(
                        blank=True, help_text="Comma-separated required skills"
                    ),
                ),
                (
                    "preferred_skills",
                    models.TextField(
                        blank=True, help_text="Comma-separated preferred skills"
                    ),
                ),
                ("external_source", models.CharField(max_length=100)),
                ("external_url", models.URLField(help_text="Original job posting URL")),
                ("is_active", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Portal Job",
                "verbose_name_plural": "Portal Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=100, unique=True)),
                (
                    "skill_category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Programming, Management, Design",
                        max_length=50,
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "occurrence_count",
                    models.PositiveIntegerField(
                        default=1, help_text="How many times this skill appeared"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Manually verified by admin"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "synonyms",
                    models.TextField(
                        blank=True, help_text="Comma-separated alternative names"
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill Master",
                "verbose_name_plural": "Skill Master",
                "ordering": ["-occurrence_count", "skill_name"],
            },
        ),
        migrations.CreateModel(
            name="StagingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_source",
                    models.CharField(
                        help_text="Source website name (e.g., seek.com.au)",
                        max_length=100,
                    ),
                ),
                ("external_url", models.URLField(help_text="Original job posting URL")),
                (
                    "external_id",
                    models.CharField(
                        blank=True, help_text="External system job ID", max_length=100
                    ),
                ),
                ("title", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("company_name", models.TextField(blank=True)),
                ("location_raw", models.TextField(blank=True)),
                ("salary_raw", models.TextField(blank=True)),
                ("job_type_raw", models.TextField(blank=True)),
                ("category_raw", models.TextField(blank=True)),
                ("posted_ago_raw", models.TextField(blank=True)),
                ("employer_contact_raw", models.TextField(blank=True)),
                ("employer_email_raw", models.TextField(blank=True)),
                ("employer_phone_raw", models.TextField(blank=True)),
                ("employer_address_raw", models.TextField(blank=True)),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Complete raw scraped data"
                    ),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_error", models.TextField(blank=True)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Staging Job",
                "verbose_name_plural": "Staging Jobs",
                "ordering": ["-scraped_at"],
            },
        ),
        migrations.CreateModel(
            name="VaultJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash_key",
                    models.CharField(
                        help_text="SHA256 hash of job URL for deduplication",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("employer_name", models.CharField(blank=True, max_length=200)),
                (
                    "employer_contact_person",
                    models.CharField(blank=True, max_length=200),
                ),
                ("employer_email", models.EmailField(blank=True, max_length=254)),
                ("employer_phone", models.CharField(blank=True, max_length=50)),
                ("employer_address", models.TextField(blank=True)),
                ("employer_website", models.URLField(blank=True)),
                ("original_title", models.CharField(max_length=500)),
                ("original_description", models.TextField()),
                ("original_url", models.URLField()),
                ("external_source", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_encrypted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether sensitive fields are encrypted",
                    ),
                ),
                (
                    "staging_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vault_records",
                        to="jobs.stagingjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vault Job",
                "verbose_name_plural": "Vault Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="stagingjob",
            index=models.Index(
                fields=["external_source", "is_processed"],
                name="jobs_stagin_externa_02f3fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stagingjob",
            index=models.Index(
                fields=["scraped_at"], name="jobs_stagin_scraped_edb4da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skillmaster",
            index=models.Index(
                fields=["skill_name"], name="jobs_skillm_skill_n_973af6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skillmaster",
            index=models.Index(
                fields=["is_active", "occurrence_count"],
                name="jobs_skillm_is_acti_c6c232_idx",
            ),
        ),
        migrations.AddField(
            model_name="portaljob",
            name="vault_job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portal_listings",
                to="jobs.vaultjob",
            ),
        ),
        migrations.AddField(
            model_name="apiadmintoken",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="vaultjob",
            index=models.Index(
                fields=["hash_key"], name="jobs_vaultj_hash_ke_f01940_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vaultjob",
            index=models.Index(
                fields=["external_source"], name="jobs_vaultj_externa_c89a82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portaljob",
            index=models.Index(
                fields=["is_active", "external_source"],
                name="jobs_portal_is_acti_e67428_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="portaljob",
            index=models.Index(
                fields=["location_city", "location_state"],
                name="jobs_portal_locatio_3fd695_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="portaljob",
            index=models.Index(
                fields=["job_category"], name="jobs_portal_job_cat_155b43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portaljob",
            index=models.Index(
                fields=["hash_key"], name="jobs_portal_hash_ke_ca2e2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiadmintoken",
            index=models.Index(
                fields=["token_key", "is_active"], name="jobs_apiadm_token_k_ff29b7_idx"
            ),
        ),
    ]
