# Generated by Django 4.2.16 on 2025-11-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0017_apiadmintoken_jobingestionsummary_portaljob_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobingestionsummary",
            options={
                "ordering": ["-summary_date", "source"],
                "verbose_name": "Job Ingestion Summary",
                "verbose_name_plural": "Job Ingestion Summaries",
            },
        ),
        migrations.AddField(
            model_name="jobingestionsummary",
            name="source",
            field=models.CharField(
                default="all_sources",
                help_text="Scraper source (e.g., apsjobs.gov.au, jobs.act.gov.au)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="jobingestionsummary",
            name="summary_date",
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name="jobingestionsummary",
            unique_together={("summary_date", "source")},
        ),
    ]
