# Generated by Django 4.2.23 on 2025-11-14 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("companies", "0007_delete_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0018_alter_jobingestionsummary_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiadmintoken",
            name="created_by",
        ),
        migrations.AlterModelOptions(
            name="portaljob",
            options={
                "ordering": ["-scraped_at"],
                "verbose_name": "Portal Job",
                "verbose_name_plural": "Portal Jobs",
            },
        ),
        migrations.RemoveIndex(
            model_name="portaljob",
            name="jobs_portal_is_acti_e67428_idx",
        ),
        migrations.RemoveIndex(
            model_name="portaljob",
            name="jobs_portal_locatio_3fd695_idx",
        ),
        migrations.RemoveIndex(
            model_name="portaljob",
            name="jobs_portal_hash_ke_ca2e2b_idx",
        ),
        migrations.RenameField(
            model_name="portaljob",
            old_name="published_at",
            new_name="date_posted",
        ),
        migrations.RenameField(
            model_name="portaljob",
            old_name="created_at",
            new_name="scraped_at",
        ),
        migrations.RemoveField(
            model_name="portaljob",
            name="company_display_name",
        ),
        migrations.RemoveField(
            model_name="portaljob",
            name="company_industry",
        ),
        migrations.RemoveField(
            model_name="portaljob",
            name="company_size",
        ),
        migrations.RemoveField(
            model_name="portaljob",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="portaljob",
            name="hash_key",
        ),
        migrations.RemoveField(
            model_name="portaljob",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="portaljob",
            name="location_city",
        ),
        migrations.RemoveField(
            model_name="portaljob",
            name="location_country",
        ),
        migrations.RemoveField(
            model_name="portaljob",
            name="location_remote",
        ),
        migrations.RemoveField(
            model_name="portaljob",
            name="location_state",
        ),
        migrations.RemoveField(
            model_name="portaljob",
            name="required_skills",
        ),
        migrations.RemoveField(
            model_name="portaljob",
            name="salary_display",
        ),
        migrations.RemoveField(
            model_name="skillmaster",
            name="first_seen",
        ),
        migrations.RemoveField(
            model_name="skillmaster",
            name="last_seen",
        ),
        migrations.RemoveField(
            model_name="skillmaster",
            name="synonyms",
        ),
        migrations.AddField(
            model_name="portaljob",
            name="additional_info",
            field=models.JSONField(
                blank=True, default=dict, help_text="Store any additional scraped data"
            ),
        ),
        migrations.AddField(
            model_name="portaljob",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portal_job_postings",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="portaljob",
            name="expired_at",
            field=models.DateTimeField(
                blank=True, help_text="When the job was marked expired", null=True
            ),
        ),
        migrations.AddField(
            model_name="portaljob",
            name="external_id",
            field=models.CharField(
                blank=True, help_text="External system job ID", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="portaljob",
            name="job_closing_date",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portaljob",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portal_jobs",
                to="core.location",
            ),
        ),
        migrations.AddField(
            model_name="portaljob",
            name="posted_ago",
            field=models.CharField(
                blank=True, help_text="Relative date like '2 days ago'", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="portaljob",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portal_posted_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="portaljob",
            name="salary_raw_text",
            field=models.CharField(
                blank=True, help_text="Original salary text", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="portaljob",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="jobs_with_skill", to="jobs.skillmaster"
            ),
        ),
        migrations.AddField(
            model_name="portaljob",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("expired", "Expired"),
                    ("filled", "Filled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="portaljob",
            name="tags",
            field=models.TextField(
                blank=True, help_text="Comma-separated tags or skills"
            ),
        ),
        migrations.AddField(
            model_name="skillmaster",
            name="preferred_skills",
            field=models.CharField(
                blank=True,
                choices=[
                    ("required", "Required Skill"),
                    ("preferred", "Preferred Skill"),
                ],
                help_text="Alternative choice classification",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="skillmaster",
            name="skills",
            field=models.CharField(
                blank=True,
                choices=[
                    ("required", "Required Skill"),
                    ("preferred", "Preferred Skill"),
                ],
                help_text="Classify if this is a required or preferred skill",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="portaljob",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="portaljob",
            name="external_source",
            field=models.CharField(default="seek.com.au", max_length=100),
        ),
        migrations.AlterField(
            model_name="portaljob",
            name="external_url",
            field=models.URLField(help_text="Original job posting URL", unique=True),
        ),
        migrations.AlterField(
            model_name="portaljob",
            name="job_category",
            field=models.CharField(
                choices=[
                    ("technology", "Technology"),
                    ("finance", "Finance"),
                    ("healthcare", "Healthcare"),
                    ("marketing", "Marketing"),
                    ("sales", "Sales"),
                    ("hr", "Human Resources"),
                    ("education", "Education"),
                    ("retail", "Retail"),
                    ("hospitality", "Hospitality"),
                    ("construction", "Construction"),
                    ("manufacturing", "Manufacturing"),
                    ("consulting", "Consulting"),
                    ("legal", "Legal"),
                    ("office_support", "Office Support"),
                    ("drivers_operators", "Drivers & Operators"),
                    ("technical_engineering", "Technical & Engineering"),
                    ("production_workers", "Production Workers"),
                    ("transport_logistics", "Transport & Logistics"),
                    ("mining_resources", "Mining & Resources"),
                    ("sales_marketing", "Sales & Marketing"),
                    ("executive", "Executive"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="portaljob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("casual", "Casual"),
                    ("contract", "Contract"),
                    ("temporary", "Temporary"),
                    ("permanent", "Permanent"),
                    ("internship", "Internship"),
                    ("freelance", "Freelance"),
                ],
                default="full_time",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="portaljob",
            name="preferred_skills",
        ),
        migrations.AlterField(
            model_name="portaljob",
            name="salary_currency",
            field=models.CharField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                ],
                default="AUD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="portaljob",
            name="salary_type",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                default="yearly",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="portaljob",
            name="work_mode",
            field=models.CharField(
                blank=True, help_text="Remote, Hybrid, On-site, etc.", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="skillmaster",
            name="occurrence_count",
            field=models.PositiveIntegerField(
                default=0, help_text="How many times this skill has been found"
            ),
        ),
        migrations.AddIndex(
            model_name="portaljob",
            index=models.Index(
                fields=["status", "external_source"],
                name="jobs_portal_status_cd1ca2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="portaljob",
            index=models.Index(
                fields=["location", "job_category"],
                name="jobs_portal_locatio_37c74c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="portaljob",
            index=models.Index(
                fields=["date_posted"], name="jobs_portal_date_po_5207ef_idx"
            ),
        ),
        migrations.DeleteModel(
            name="ApiAdminToken",
        ),
        migrations.AddField(
            model_name="portaljob",
            name="preferred_skills",
            field=models.ManyToManyField(
                blank=True, related_name="jobs_preferring_skill", to="jobs.skillmaster"
            ),
        ),
    ]
