# Generated by Django 4.2.16 on 2025-11-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0019_remove_apiadmintoken_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobscheduler",
            name="source_name",
            field=models.CharField(
                blank=True,
                help_text="Source identifier for JobIngestionSummary (e.g., jobs.act.gov.au, seek.com.au)",
                max_length=100,
                null=True,
            ),
        ),
    ]
