# Generated by Django 4.2.16 on 2025-11-17 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0020_add_source_name_to_jobscheduler"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "portal_name",
                    models.CharField(
                        help_text="Portal display name (e.g., TBD Project PC)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "portal_slug",
                    models.SlugField(help_text="URL-friendly identifier", unique=True),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable/disable this portal"
                    ),
                ),
                (
                    "server_url",
                    models.URLField(
                        help_text="API endpoint URL where data will be sent"
                    ),
                ),
                (
                    "access_token",
                    models.CharField(help_text="Portal access token", max_length=500),
                ),
                (
                    "token_secret",
                    models.CharField(help_text="Portal token secret", max_length=500),
                ),
                (
                    "encryption_key",
                    models.CharField(help_text="Fernet encryption key", max_length=500),
                ),
                (
                    "job_limit",
                    models.IntegerField(
                        default=100, help_text="Maximum jobs to send per sync cycle"
                    ),
                ),
                (
                    "sync_interval",
                    models.IntegerField(
                        default=60, help_text="Seconds between sync cycles"
                    ),
                ),
                (
                    "send_all_jobs",
                    models.BooleanField(
                        default=False,
                        help_text="If True, send ALL jobs (ignore time filtering)",
                    ),
                ),
                (
                    "allowed_sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed sources e.g., ['seek', 'act_gov']. Empty = all sources",
                    ),
                ),
                (
                    "allowed_statuses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed statuses e.g., ['active', 'closed']. Empty = all statuses",
                    ),
                ),
                (
                    "allowed_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed job categories. Empty = all categories",
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, help_text="When the last sync completed", null=True
                    ),
                ),
                (
                    "last_sync_status",
                    models.CharField(
                        blank=True, help_text="Success/failed/timeout", max_length=20
                    ),
                ),
                ("total_syncs", models.PositiveIntegerField(default=0)),
                ("successful_syncs", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Portal Configuration",
                "verbose_name_plural": "Portal Configurations",
                "ordering": ["portal_name"],
            },
        ),
        migrations.AddField(
            model_name="tbl_job_transmission_log",
            name="portal",
            field=models.ForeignKey(
                blank=True,
                help_text="Which portal this transmission was sent to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transmissions",
                to="jobs.portalconfiguration",
            ),
        ),
    ]
