# Generated by Django 4.2.23 on 2025-11-17 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0021_add_portal_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbl_job_transmission_items",
            name="job_posting",
            field=models.ForeignKey(
                blank=True,
                help_text="Original PortalJob",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.portaljob",
            ),
        ),
    ]
