# Generated by Django 4.2.23 on 2025-11-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0022_alter_tbl_job_transmission_items_job_posting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portalconfiguration",
            name="access_token",
            field=models.CharField(
                blank=True, help_text="Portal access token", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="portalconfiguration",
            name="encryption_key",
            field=models.CharField(
                blank=True, help_text="Fernet encryption key", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="portalconfiguration",
            name="token_secret",
            field=models.CharField(
                blank=True, help_text="Portal token secret", max_length=500, null=True
            ),
        ),
    ]
